config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get "welcome/index"
  get "farmers/weather"
  get "farmers/dollars"
  root "welcome#index"
  resources :farmers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  attr_accessor :avatar_file_name
  belongs_to :user
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '600x600#',
    medium: '300x300>'
  }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :farmers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
   end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController

  def weather
  end

  def dollars
  end

  def index
    @farmers = Farmer.all
  end 

  def new
    @farmer = Farmer.new
  end

  def create
    # binding.pry
    @farmer = current_user.farmers.new(farmer_params)
    respond_to do |format|
    if @farmer.save
        format.html { redirect_to @farmer, notice: "Thank you for giving and for supporting the community and adding a farmers market"}
        format.js {}
        format.json {render json: @farmer, status: :created, location: @farmer}
      else
        format.html { redirect_to @farmer, notice: "Sorry, your farmer market was not added"}
        format.js {}
        format.json { render json: @farmer, notice: "Please try to add a market again"}
      end
    end
  end

  def show
    @farmer = Farmer.find(params[:id])
  end  

  private

  def farmer_params
    params.require(:farmer).permit(:farmer_market_name, :speciality, :schedule, :price_range, :avatar) 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
  def dollar_sign
    binding.pry
    ranged_num = @farmer.price_range.split("-").map(&:to_i)
    range = ranged_num[0]..ranged_num[1]
    if range.include?(1..20)
      "$" 
    elsif range.include?(20..35)
      "$$" 
    elsif range.include?(35..50)
      "$$$" 
    elsif range.include?(50..ranged_num[1])
      "$$$$" 
    else
      @farmer.price_range
    end
  end          
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/farmers/_form.html.erb
  <div class="text-center">
  <h1>Create a Market</h1>
  <%= form_for @farmer, :multipart => true do |f| %>
  <div>
  <%= f.label :farmer_market_name%>
  <%= f.text_field :farmer_market_name, class:"form-control"%>
  </div>

  <div >
  <%=f.label :schedule%>
  <%=f.text_field :schedule, class:"form-control"%>
  </div>

  <div>
  <%=f.file_field :avatar, class:"form-control" %> 
  </div>

  <div>
  <%=f.label :speciality%>
  <%=f.text_area :speciality, class:"form-control"%>
  </div>

  <%=f.label :price_range%>
  <%=f.text_field :price_range, class:"form-control"%>
  <%=f.submit "Create"%>
  <%end%>

</div>

app/views/farmers/dollars.html.erb
<div class="text-center">
<h1><u>Dollar Signs</u></h1>
<p>We have set up a few conventions farmer market creators should know how to use</p>
<p>Knowing the price range and how many dollar signs it creates is important!</p>
<div>
  <h2>$ = 1-20</h2>
  <h2>$$ = 20-35</h2>
  <h2>$$$ = 35-50</h2>
  <h2>$$$$ = 50+</h2>
  <p>These guidelines should help you inform your customers</p>
  <p>If your price cannont be represented above it will just show the numbers</p>    
</div>
</div>

app/views/farmers/index.html.erb
<% @farmers.each do |farmer| %> 
  <div class="square">
    <%= link_to image_tag(farmer.avatar.url(:medium).to_s, :class => "hover"), farmer_url(farmer.id), title:farmer.farmer_market_name %>
      </div>
     </div>  
     <%end%>

app/views/farmers/new.html.erb
<%=render"farmers/form"%>

app/views/farmers/show.html.erb
<div class="text-center">
<h1><%=@farmer.farmer_market_name%></h1>

<%= image_tag @farmer.avatar.url(:square)%>
<h2><%=@farmer.schedule%></h2>
<p><%=@farmer.speciality%></p>
<h2><%=dollar_sign%></h2>
</div>

app/views/farmers/weather.html.erb
<div class="text-center">
<h1><u>Weather</u></h1>
<p>How does weather effect a farmers market?</p>
<p> it can effect the overall turnout for your market and being prepared with the nescerary equipment will help reviews</p>
<p> So when you sumbit your market it will also show you the weather and the weather farmer market goingers</p>
<p>If you have any questions please contact us!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheFarmerMarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://blackrockdigital.github.io/startbootstrap-stylish-portfolio/css/stylish-portfolio.css" rel="stylesheet">
 </head>

  <body>
  <body cz-shortcut-listen="true">
 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                      </button>
                       <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i> <span class="light" style="color:black">The Farmer Market</span> 
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                  <li class="" >
                    <%if user_signed_in?%>
                      <a <%= link_to "Logout", destroy_user_session_path, :style =>"color:black", method: :delete, :class => "page-scroll"%></a>  
                            <%else%>
                          </li>
                        <li class="">
                      <a <%= link_to "Login", user_session_path, :style =>"color:black", :class => "page-scroll"%> </a>  
                    </li>
                  <%end%>
                <li class="">                              
              <a <%= link_to "Home", welcome_index_path, :style =>"color:black", :class => "page-scroll"%></a>  
            </li>
            <li class="">                              
              <a <%= link_to "Add", new_farmer_path, :style =>"color:black", :class => "page-scroll"%></a>  
            </li>
            <li class="">                              
              <a <%= link_to "Index", farmers_path, :style =>"color:black", :class => "page-scroll"%></a>  
            </li>
          </ul>
            </div>
              <div class="row">
                 <div class="col-xs-10 col-xs-offset-1">
                      <% flash.each do |alert_type, msg| %>
                          <% if alert_type == "notice" %>
                             <div class="alert alert-success">
                                <% elsif alert_type == "alert" %>
                                  <div class="alert alert-danger">
                                    <% else %>
                               <div class="alert-dismissible<%= "#{alert_type}"%>" >
                              <% end %>
                           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <ul>
                      <li>
                   <%= msg %>
                 </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
     <!-- /.container -->
    </nav>
    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>The Farmer Market</h1>
            <br>
        </div>
    </header>
<%= yield %>
    <!-- Footer -->


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <hr class="small">
                    <p class="text-muted">Copyright © Rafeeq Wilson 2016</p>
                </div>
            </div>
        </div>
       
    </footer>

    
  </body>
</html>

app/views/welcome/index.html.erb
  <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1>About</h1>
                    <p> Using this website you can upload your farmers market</p>
                    <p> You can display your speacialities you have at a farmer market</p>
                    <p> You can add the how much one can expect to spend</p>
                    <p>And one can donate </p>  
                </div>
            </div> 
    </section> 
    <section id="services" class="services bg-primary">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>Our Services</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Donate</strong>
                                </h4>
                                <p>Learn how you can donate and help our community</p>
                                <a href="#" class="btn btn-light">Learn More</a>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-compass fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Dollar Signs</strong>
                                </h4>
                                <p>What amounts indicate the amount of dollars signs</p>
                                 <%=link_to "Learn More",farmers_dollars_path, class:"btn btn-light"%>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-flask fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Weather</strong>
                                </h4>
                                <p>Weather function allows you be prepared</p>
                                
                                <%=link_to "Learn More",farmers_weather_path, class:"btn btn-light"%>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-shield fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Service Name</strong>
                                </h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
                                <a href="#" class="btn btn-light">Learn More</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

  <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1>Contact</h1>
                    <ul class="list-unstyled">    
                      <h4><strong>Farmer Market</strong>
                    </h4>
                    <p>
                      San Francisco
                      <br> Farmers Market 123 lane
                    </p>
                        <li>
                        <a href="https://github.com/rafeeq-123" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>


                        </li>
                        <i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:rafeeqwilson914@gmail.com">rafeeqwilson914@gmail.com</a>
                    
                    </ul>
                    <br>
                    <ul class="list-inline">
                </div>
            </div> 
    </section> 
    <!-- Callout -->
    <aside class="callout">
        <div class="text-vertical-center">
            <h1>Vertically Centered Text</h1>
        </div>
    </aside>